//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplePie {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class ApplePieConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApplePieConfiguration defaultInstance = ((ApplePieConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApplePieConfiguration())));
        
        public static ApplePieConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableApplePie {
            get {
                return ((bool)(this["EnableApplePie"]));
            }
            set {
                this["EnableApplePie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebConfigPath {
            get {
                return ((string)(this["WebConfigPath"]));
            }
            set {
                this["WebConfigPath"] = value;
            }
        }
    }
}
